// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestEF.ClassLibrary1;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20251116163652_mn")]
    partial class mn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestEF.ClassLibrary1.Course", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("unit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SemesterID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.Semester", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime2");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("average")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.aqt", b =>
                {
                    b.Property<int>("id5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id5"));

                    b.Property<int?>("bqtID1")
                        .HasColumnType("int");

                    b.Property<int?>("bqtID2")
                        .HasColumnType("int");

                    b.Property<int?>("lastID")
                        .HasColumnType("int");

                    b.HasKey("id5");

                    b.HasIndex("bqtID1");

                    b.HasIndex("bqtID2");

                    b.HasIndex("lastID");

                    b.ToTable("aqt4");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.bqt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("bqt4");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.cqt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("cqt4");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.r", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("aqtID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("aqtID");

                    b.ToTable("r");
                });

            modelBuilder.Entity("aqtcqt", b =>
                {
                    b.Property<int>("aqtid5")
                        .HasColumnType("int");

                    b.Property<int>("cqtid")
                        .HasColumnType("int");

                    b.HasKey("aqtid5", "cqtid");

                    b.HasIndex("cqtid");

                    b.ToTable("aqtcqt");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.Enrollment", b =>
                {
                    b.HasOne("TestEF.ClassLibrary1.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestEF.ClassLibrary1.Semester", "semester")
                        .WithMany()
                        .HasForeignKey("SemesterID");

                    b.HasOne("TestEF.ClassLibrary1.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("semester");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.aqt", b =>
                {
                    b.HasOne("TestEF.ClassLibrary1.bqt", "bqt1")
                        .WithMany("aqt1")
                        .HasForeignKey("bqtID1");

                    b.HasOne("TestEF.ClassLibrary1.bqt", "bqt2")
                        .WithMany("aqt2")
                        .HasForeignKey("bqtID2");

                    b.HasOne("TestEF.ClassLibrary1.r", "last")
                        .WithMany("aqt2")
                        .HasForeignKey("lastID");

                    b.Navigation("bqt1");

                    b.Navigation("bqt2");

                    b.Navigation("last");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.r", b =>
                {
                    b.HasOne("TestEF.ClassLibrary1.aqt", "aqt1")
                        .WithMany("history")
                        .HasForeignKey("aqtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aqt1");
                });

            modelBuilder.Entity("aqtcqt", b =>
                {
                    b.HasOne("TestEF.ClassLibrary1.aqt", null)
                        .WithMany()
                        .HasForeignKey("aqtid5")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestEF.ClassLibrary1.cqt", null)
                        .WithMany()
                        .HasForeignKey("cqtid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.aqt", b =>
                {
                    b.Navigation("history");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.bqt", b =>
                {
                    b.Navigation("aqt1");

                    b.Navigation("aqt2");
                });

            modelBuilder.Entity("TestEF.ClassLibrary1.r", b =>
                {
                    b.Navigation("aqt2");
                });
#pragma warning restore 612, 618
        }
    }
}
